# Generated by Django 5.2.5 on 2025-08-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('pow', 'Power'), ('fibonacci', 'Fibonacci'), ('factorial', 'Factorial')], max_length=20)),
                ('input_data', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
