# Generated by Django 5.2.5 on 2025-08-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user2fa_totp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user2fa',
            name='totp_secret',
        ),
    ]
