# Generated by Django 5.2.5 on 2025-08-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user2fa_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2fa',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
