# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - django-react-app-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write # Adjusted permissions at job level

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Python and install dependencies
        working-directory: backend
        shell: pwsh
        run: |
          python -m venv venv
            .\venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database migrations
        working-directory: backend
        shell: pwsh
        run: |
          .\venv\Scripts\Activate.ps1
          python manage.py migrate

      - name: Collect static files
        working-directory: backend
        shell: pwsh
        run: |
          .\venv\Scripts\Activate.ps1
          python manage.py collectstatic --noinput



  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write # Adjusted permissions at job level
      contents: read

    steps:

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}


      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-backend
        with:
          app-name: 'django-react-app-backend'
          slot-name: 'Production'
          package: backend/release.zip



      # Detailed comments added for each step

      # Step: Run frontend tests
      # Purpose: Validate the functionality of the React application

      # Step: Monitor application status
      # Purpose: Check for errors and ensure the application is running smoothly post-deployment
