name: Build and test Django backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: backend
        shell: pwsh
        run: |
          python -m venv venv
          venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        working-directory: backend
        shell: pwsh
        run: |
          venv\Scripts\activate
          python manage.py migrate

      - name: Collect static files
        working-directory: backend
        shell: pwsh
        run: |
          venv\Scripts\activate
          python manage.py collectstatic --noinput

      - name: Run tests
        working-directory: backend
        shell: pwsh
        run: |
          venv\Scripts\activate
          python manage.py test