name: Build and test Python app - django-react-app-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Python and install dependencies
        working-directory: backend
        shell: pwsh
        run: |
          python -m venv venv
          venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database migrations
        working-directory: backend
        shell: pwsh
        run: |
          venv\Scripts\activate
          python manage.py migrate

      - name: Collect static files
        working-directory: backend
        shell: pwsh
        run: |
          venv\Scripts\activate
          python manage.py collectstatic --noinput

      - name: Run backend tests
        working-directory: backend
        shell: pwsh
        run: |
          venv\Scripts\activate
          python manage.py test
      # Step: Upload artifact (optional, only if you need to use it in other jobs)
      # uses: actions/upload-artifact@v4
      # with:
      #   name: python-app
      #   path: |
      #     backend/release.zip
      #     !venv/